services:
  - type: web
    name: farmacia
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
    startCommand: php -S 0.0.0.0:8080 -t public


