server {
    listen 80;
    index index.php index.html;
    root /var/www/html/public;

    # Evitar que se liste directorios
    autoindex off;

    location /build/ {
    alias /var/www/html/public/build/;
    access_log off;
    expires max;
}

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM (escucha en TCP 127.0.0.1:9000 por la configuración por defecto)
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    # Denegar accesos a ficheros ocultos
    location ~ /\.(?!well-known).* {
        deny all;
    }
}



